mininit.c: klibc specific fix around missing setlinebuf
Klibc has buffered I/O since v. 2.0 but still lacks some streeam functions.

Fixing:
| mininit.o: In function `main':
| mininit.c:(.text.startup+0x70): undefined reference to `setlinebuf'

Signed-off-by: Andrea Adami <andrea.adami@gmail.com>